module.exports={
  BASE_URL:'http://localhost:3000/',
  EMAIL_ADDRESS:'https://mail.163.com/',
  ROOT_CODE:'Zswsown',
  ROOT_PASSWORD:'314356',
  api:{
    SELECT_BLOGS:'api/getBlogList',
    DELETE_BLOG:'api/deleteBlog',
    DELETE_MESSAGE:"api/deleteMessage",
    DELETE_MESSAGES:'api/deleteMessages',
    SELECT_MESSAGE_LIST:'api/selectMessageList',
    INSERT_MATERIAL:'api/insertMaterial',
    INSERT_MATERIAL_ICON:'api/insertMaterialIcon',
  }
}