export const BASE_URL="http://localhost:3000/api/"
export const api={
  SELECT_BLOG:"selectBlog",
  DELETE_BLOG:"deleteBlog",
  INSERT_BLOG:"insertBlog",
  UPDATE_BLOG:"updateBlog",
  SELECT_BLOGS:'getBlogList',
  INSERT_IMAGES:"insertImages",
  SELECT_MESSAGE:"selectMessage",
  DELETE_MESSAGE:"deleteMessage",
  INSERT_MESSAGE:"insertMessage",
  UPDATE_MESSAGE:"updateMessage",
  INSERT_QUOTE_MESSAGE:'insertQuoteMessage',
  SELECT_QUOTE_MESSAGE:'selectQuoteMessage',
  INSERT_REPLY_MESSAGE:'insertReplyMessage',
  SELECT_REPLY_MESSAGE:'selectReplyMessage',
  SELECT_MESSAGE_LIST:'selectMessageList',
  LOGIN_CHECK:'loginCheck',
  LOGIN:'login',
}
